name: check_completeness
run-name: Check translations completeness
on: [push, workflow_dispatch]
jobs:
  Check-Completeness:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Shopkeepers-Language-Files
         
      - name: Checkout helper repo
        uses: actions/checkout@v4
        with:
          repository: Zkir/Shopkeepers-Language-Files-Helpers
          path: Shopkeepers-Language-Files-Helpers
            
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 #install the python needed
          
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r Shopkeepers-Language-Files-Helpers/requirements.txt
        
      - name: execute py script # run file
        run: |
          (cd Shopkeepers-Language-Files-Helpers; python check_translations.py --MD)
